# Generated by Django 3.1.5 on 2021-02-27 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangerate',
            old_name='created',
            new_name='created_time',
        ),
    ]
