# Generated by Django 3.1.5 on 2021-02-28 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger', '0002_auto_20210227_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerate',
            name='buy_status',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='sale_status',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
        ),
    ]
