# Generated by Django 3.1.5 on 2021-02-28 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchanger', '0003_auto_20210228_2255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangerate',
            old_name='sale_status',
            new_name='sell_status',
        ),
    ]
