# Generated by Django 3.1.5 on 2021-03-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='photo',
            field=models.ImageField(default='photos/default.png', upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='photos/default.png', upload_to='photos/'),
        ),
    ]
