# Generated by Django 3.1.5 on 2021-03-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_auto_20210313_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=150),
        ),
    ]
